[package]
name = "trackvault"
version = "0.1.0"
description = "TrackVault — local music library player"
authors = ["you"]
edition = "2021"

[lib]
name = "trackvault_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
lofty = "0.22"
symphonia = { version = "0.5", features = ["mp3", "flac", "wav", "aac", "vorbis", "isomp4"] }
rodio = { version = "0.19", features = ["symphonia-mp3", "symphonia-flac", "symphonia-wav", "symphonia-aac", "symphonia-vorbis", "symphonia-isomp4"] }
walkdir = "2"
thiserror = "2"
parking_lot = "0.12"
