import type { AppearanceSettings } from "./appearance";

export type ColorSchemeMode = "light" | "dark";

export interface ColorScheme {
  id: string;
  name: string;
  description: string;
  mode: ColorSchemeMode;
  colors: AppearanceSettings;
}

export const DEFAULT_SCHEME_ID = "trackvault";

const trackvault: AppearanceSettings = {
  background: "#0a0a0a",
  surface: "#171717",
  surfaceHover: "#262626",
  border: "#262626",
  foreground: "#f5f5f5",
  muted: "#a3a3a3",
  accent: "#2563eb",
  accentHover: "#3b82f6",
  accentSubtle: "#172554",
  dropIndicator: "#38bdf8",
  playingText: "#93c5fd",
  cursorBackground: "#262626",
  cursorBackgroundPlaying: "#1e3a5f",
  waveformWave: "#525252",
  waveformProgress: "#60a5fa",
  waveformCursor: "#ffffff",
};

export const COLOR_SCHEMES: ColorScheme[] = [
  {
    id: "trackvault",
    name: "IceTrackVault",
    description: "Classic blue accent on dark gray",
    mode: "dark",
    colors: trackvault,
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "Deep blue-violet shell with indigo highlights",
    mode: "dark",
    colors: {
      background: "#0c0a14",
      surface: "#161320",
      surfaceHover: "#221e30",
      border: "#2d2840",
      foreground: "#ede9fe",
      muted: "#a5b4c8",
      accent: "#6366f1",
      accentHover: "#818cf8",
      accentSubtle: "#1e1b4b",
      dropIndicator: "#a5b4fc",
      playingText: "#c4b5fd",
      cursorBackground: "#221e30",
      cursorBackgroundPlaying: "#312e81",
      waveformWave: "#4b5563",
      waveformProgress: "#818cf8",
      waveformCursor: "#ede9fe",
    },
  },
  {
    id: "forest",
    name: "Forest",
    description: "Dark greens with a natural emerald accent",
    mode: "dark",
    colors: {
      background: "#0a120c",
      surface: "#111f14",
      surfaceHover: "#1a3020",
      border: "#234830",
      foreground: "#ecfdf5",
      muted: "#86a894",
      accent: "#16a34a",
      accentHover: "#22c55e",
      accentSubtle: "#14532d",
      dropIndicator: "#4ade80",
      playingText: "#86efac",
      cursorBackground: "#1a3020",
      cursorBackgroundPlaying: "#166534",
      waveformWave: "#4b5563",
      waveformProgress: "#4ade80",
      waveformCursor: "#ecfdf5",
    },
  },
  {
    id: "ember",
    name: "Ember",
    description: "Warm dark tones with amber highlights",
    mode: "dark",
    colors: {
      background: "#120e0a",
      surface: "#1f1810",
      surfaceHover: "#302818",
      border: "#483820",
      foreground: "#fef3c7",
      muted: "#a89880",
      accent: "#d97706",
      accentHover: "#f59e0b",
      accentSubtle: "#451a03",
      dropIndicator: "#fbbf24",
      playingText: "#fcd34d",
      cursorBackground: "#302818",
      cursorBackgroundPlaying: "#78350f",
      waveformWave: "#57534e",
      waveformProgress: "#fbbf24",
      waveformCursor: "#fef3c7",
    },
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    description: "Maximum separation for clarity",
    mode: "dark",
    colors: {
      background: "#000000",
      surface: "#141414",
      surfaceHover: "#262626",
      border: "#404040",
      foreground: "#ffffff",
      muted: "#c0c0c0",
      accent: "#3b82f6",
      accentHover: "#60a5fa",
      accentSubtle: "#1e3a8a",
      dropIndicator: "#60a5fa",
      playingText: "#93c5fd",
      cursorBackground: "#262626",
      cursorBackgroundPlaying: "#1e40af",
      waveformWave: "#737373",
      waveformProgress: "#60a5fa",
      waveformCursor: "#ffffff",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    description: "Developer classic tuned for music UI",
    mode: "dark",
    colors: {
      background: "#272822",
      surface: "#32332a",
      surfaceHover: "#3e3f35",
      border: "#49483e",
      foreground: "#f8f8f2",
      muted: "#a8a89a",
      accent: "#66d9ef",
      accentHover: "#8be9fd",
      accentSubtle: "#1e3a40",
      dropIndicator: "#a6e22e",
      playingText: "#a6e22e",
      cursorBackground: "#3e3f35",
      cursorBackgroundPlaying: "#2d4a28",
      waveformWave: "#75715e",
      waveformProgress: "#a6e22e",
      waveformCursor: "#f8f8f2",
    },
  },
  {
    id: "charcoal",
    name: "Paper",
    description: "Clean neutral palette on a light background",
    mode: "light",
    colors: {
      background: "#f5f5f5",
      surface: "#ffffff",
      surfaceHover: "#f0f0f0",
      border: "#e5e5e5",
      foreground: "#171717",
      muted: "#737373",
      accent: "#525252",
      accentHover: "#404040",
      accentSubtle: "#f5f5f5",
      dropIndicator: "#737373",
      playingText: "#404040",
      cursorBackground: "#f0f0f0",
      cursorBackgroundPlaying: "#e5e5e5",
      waveformWave: "#d4d4d4",
      waveformProgress: "#525252",
      waveformCursor: "#171717",
    },
  },
  {
    id: "ocean",
    name: "Seafoam",
    description: "Pale cyan shell with teal accents",
    mode: "light",
    colors: {
      background: "#f0fdfa",
      surface: "#ffffff",
      surfaceHover: "#ecfdf5",
      border: "#ccfbf1",
      foreground: "#134e4a",
      muted: "#5f8a87",
      accent: "#0d9488",
      accentHover: "#0f766e",
      accentSubtle: "#ecfdf5",
      dropIndicator: "#14b8a6",
      playingText: "#0f766e",
      cursorBackground: "#ecfdf5",
      cursorBackgroundPlaying: "#ccfbf1",
      waveformWave: "#99f6e4",
      waveformProgress: "#0d9488",
      waveformCursor: "#134e4a",
    },
  },
  {
    id: "slate",
    name: "Daylight",
    description: "Cool gray-blue professional light theme",
    mode: "light",
    colors: {
      background: "#f1f5f9",
      surface: "#ffffff",
      surfaceHover: "#e2e8f0",
      border: "#cbd5e1",
      foreground: "#0f172a",
      muted: "#64748b",
      accent: "#475569",
      accentHover: "#334155",
      accentSubtle: "#e2e8f0",
      dropIndicator: "#64748b",
      playingText: "#334155",
      cursorBackground: "#e2e8f0",
      cursorBackgroundPlaying: "#cbd5e1",
      waveformWave: "#cbd5e1",
      waveformProgress: "#475569",
      waveformCursor: "#0f172a",
    },
  },
  {
    id: "rose",
    name: "Blush",
    description: "Soft pink tint on white",
    mode: "light",
    colors: {
      background: "#fdf2f8",
      surface: "#ffffff",
      surfaceHover: "#fce7f3",
      border: "#fbcfe8",
      foreground: "#831843",
      muted: "#9d7185",
      accent: "#db2777",
      accentHover: "#be185d",
      accentSubtle: "#fce7f3",
      dropIndicator: "#ec4899",
      playingText: "#be185d",
      cursorBackground: "#fce7f3",
      cursorBackgroundPlaying: "#fbcfe8",
      waveformWave: "#f9a8d4",
      waveformProgress: "#db2777",
      waveformCursor: "#831843",
    },
  },
  {
    id: "violet",
    name: "Lavender",
    description: "Pale purple shell with violet accents",
    mode: "light",
    colors: {
      background: "#f5f3ff",
      surface: "#ffffff",
      surfaceHover: "#ede9fe",
      border: "#ddd6fe",
      foreground: "#4c1d95",
      muted: "#7c6b9e",
      accent: "#7c3aed",
      accentHover: "#6d28d9",
      accentSubtle: "#ede9fe",
      dropIndicator: "#8b5cf6",
      playingText: "#6d28d9",
      cursorBackground: "#ede9fe",
      cursorBackgroundPlaying: "#ddd6fe",
      waveformWave: "#c4b5fd",
      waveformProgress: "#7c3aed",
      waveformCursor: "#4c1d95",
    },
  },
  {
    id: "copper",
    name: "Sand",
    description: "Warm cream background with rust accents",
    mode: "light",
    colors: {
      background: "#faf5f0",
      surface: "#ffffff",
      surfaceHover: "#f5ebe0",
      border: "#e7d5c4",
      foreground: "#431407",
      muted: "#8b7355",
      accent: "#b45309",
      accentHover: "#92400e",
      accentSubtle: "#ffedd5",
      dropIndicator: "#d97706",
      playingText: "#92400e",
      cursorBackground: "#f5ebe0",
      cursorBackgroundPlaying: "#fed7aa",
      waveformWave: "#d6c4b0",
      waveformProgress: "#b45309",
      waveformCursor: "#431407",
    },
  },
];

const schemeById = new Map(COLOR_SCHEMES.map((scheme) => [scheme.id, scheme]));

export function isValidSchemeId(id: string): boolean {
  return schemeById.has(id);
}

export function getScheme(id: string): ColorScheme {
  return schemeById.get(id) ?? schemeById.get(DEFAULT_SCHEME_ID)!;
}

export function getSchemeColors(id: string): AppearanceSettings {
  return getScheme(id).colors;
}

export function getSchemesByMode(mode: ColorSchemeMode): ColorScheme[] {
  return COLOR_SCHEMES.filter((scheme) => scheme.mode === mode);
}

export const VALID_SCHEME_IDS = COLOR_SCHEMES.map((scheme) => scheme.id);
